parameters:
#    pronit_gestion_materiales.example.class: Pronit\GestionMaterialesBundle\Example

services:
#    pronit_gestion_materiales.example:
#        class: %pronit_gestion_materiales.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
