imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @PronitCoreBundle/Resources/config/admin.yml }
    - { resource: @PronitEstructuraEmpresaBundle/Resources/config/admin.yml }
    - { resource: @PronitParametrizacionGeneralBundle/Resources/config/admin.yml }
    - { resource: @PronitGeographicCoreBundle/Resources/config/admin.yml }
    - { resource: @PronitCustomizingBundle/Resources/config/admin.yml }
    - { resource: @PronitGestionBienesYServiciosBundle/Resources/config/admin.yml }
    - { resource: @PronitComprasBundle/Resources/config/admin.yml }
    - { resource: @PronitAutomatizacionBundle/Resources/config/admin.yml }
    
framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            true
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'InfiniteFormBundle::form_theme.html.twig'
            - 'InfiniteFormBundle::collection_theme.html.twig'            
            - 'SonataCoreBundle:Form:datepicker.html.twig'            
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ PronitCoreBundle, PronitComprasBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less: 
            node: C:\Program Files\nodejs\node.exe
            node_paths: [C:\Users\Pocha\node_modules]
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true                
                  

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]            
        # Your other blocks

sonata_admin:
    title: PronIT
    title_logo: bundles/pronitcore/img/logo.png
    security:
        handler: sonata.admin.security.handler.role
    options:
        form_type: horizontal
    templates:
        layout: PronitCoreBundle:Sonata:standard_layout.html.twig
    assets:
        stylesheets:
            - bundles/pronitcore/vendor/bootstrap/dist/css/bootstrap.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager