pronit_parametrizacion_general:
    resource: "@PronitParametrizacionGeneralBundle/Resources/config/routing.yml"
    prefix:   /

pronit_estructura_empresa:
    resource: "@PronitEstructuraEmpresaBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin