services:
    pronit.admin.compras.pedido:
        class: Pronit\ComprasBundle\Admin\Documentos\Pedidos\PedidoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Compras", label: "Pedido de Compra" }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\Pedidos\Pedido
            - 'PronitComprasBundle:Documentos\Pedidos\Pedido'
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]
            
    pronit.admin.compras.itempedido:
        class: Pronit\ComprasBundle\Admin\Documentos\Pedidos\ItemPedidoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\Pedidos\ItemPedido
            - ~
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]
            
    pronit.admin.compras.customizing.acreedores.proveedor_sociedadfi:
        class: Pronit\ComprasBundle\Admin\Customizing\Acreedores\ProveedorSociedadFIAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Customizing Sociedad FI", label: "Gestión de Proveedores" }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Customizing\Acreedores\ProveedorSociedadFI
            - ~
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]   

    pronit.admin.compras.entradasmercancias.entradamercancias:
        class: Pronit\ComprasBundle\Admin\Documentos\EntradasMercancias\EntradaMercanciasAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Compras", label: "Entrada de Mercancías" }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\EntradasMercancias\EntradaMercancias
            - 'PronitComprasBundle:Documentos\EntradasMercancias\EntradaMercancias'
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]
            
    pronit.admin.compras.entradasmercancias.itementradamercancias:
        class: Pronit\ComprasBundle\Admin\Documentos\EntradasMercancias\ItemEntradaMercanciasAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\EntradasMercancias\ItemEntradaMercancias
            - ~
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]

    pronit.admin.compras.factura:
        class: Pronit\ComprasBundle\Admin\Documentos\Facturas\FacturaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Compras", label: "Factura" }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\Facturas\Factura
            - 'PronitComprasBundle:Documentos\Facturas\Factura'
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]
            
    pronit.admin.compras.facturas.itemfactura:
        class: Pronit\ComprasBundle\Admin\Documentos\Facturas\ItemFacturaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\Facturas\ItemFactura
            - ~
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]

    pronit.admin.compras.ordenpago:
        class: Pronit\ComprasBundle\Admin\Documentos\OrdenesPago\OrdenPagoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Compras", label: "Orden de Pago" }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\OrdenesPago\OrdenPago
            - 'PronitComprasBundle:Documentos\OrdenesPago\OrdenPago'
        calls:
            - [ setTemplate, [edit, PronitComprasBundle:Documentos\\OrdenPago\\CRUD:edit.html.twig]]            
            - [ setTranslationDomain, [PronitComprasBundle]]

    pronit.admin.compras.ordenespago.itemordenpago:
        class: Pronit\ComprasBundle\Admin\Documentos\OrdenesPago\ItemOrdenPagoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\OrdenesPago\ItemOrdenPago
            - ~
        calls:
            - [ setTemplate, [edit, PronitComprasBundle:Documentos\\ItemOrdenPago\\CRUD:edit.html.twig]]            
            - [ setTranslationDomain, [PronitComprasBundle]]

    pronit.admin.compras.ordenespago.itempago:
        class: Pronit\ComprasBundle\Admin\Documentos\OrdenesPago\ItemPagoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\ComprasBundle\Entity\Documentos\OrdenesPago\ItemPago
            - ~
        calls:
            - [ setTranslationDomain, [PronitComprasBundle]]
