parameters:
    pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable.class: Pronit\ComprasBundle\Model\Contabilidad\Esquemas\EntradasMercancias\GeneradorEsquemaContable
    pronit_compras_contabilidad_esquemas_facturas.generador_esquema_contable.class: Pronit\ComprasBundle\Model\Contabilidad\Esquemas\Facturas\GeneradorEsquemaContable
    pronit_compras_transaccion.entradamercancias.class: Pronit\ComprasBundle\Model\Transacciones\EntradasMercancias\TransaccionEntradaMercancias
    pronit_compras_transaccion.factura.class: Pronit\ComprasBundle\Model\Transacciones\Facturas\TransaccionFactura

services:
    pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable:
        class: %pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_customizing.operaciones_customizing_manager, @pronit_gestion_bienesyservicios_customizing_contabilidad.imputaciones_manager, @pronit_contabilidad_customizing.imputaciones_manager]        

    pronit_compras_contabilidad_esquemas_facturas.generador_esquema_contable:
        class: %pronit_compras_contabilidad_esquemas_facturas.generador_esquema_contable.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_customizing.operaciones_customizing_manager, @pronit_gestion_bienesyservicios_customizing_contabilidad.imputaciones_manager, @pronit_contabilidad_customizing.imputaciones_manager]

    pronit_compras_transaccion.entradamercancias:
        class: %pronit_compras_transaccion.entradamercancias.class%

        arguments: [@doctrine.orm.entity_manager, @pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable, @pronit_contabilidad_customizing.generador_asientos_contables]
        
    pronit_compras_transaccion.factura:
        class: %pronit_compras_transaccion.factura.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_compras_contabilidad_esquemas_facturas.generador_esquema_contable, @pronit_contabilidad_customizing.generador_asientos_contables]
