parameters:
    pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable.class: Pronit\ComprasBundle\Model\Contabilidad\Esquemas\EntradasMercancias\GeneradorEsquemaContable

services:
    pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable:
        class: %pronit_compras_contabilidad_esquemas_entradasmercancias.generador_esquema_contable.class%
        arguments: [@pronit_customizing.operaciones_customizing_manager, @pronit_gestion_bienesyservicios_customizing_contabilidad.imputaciones_manager, @pronit_contabilidad_customizing.imputaciones_manager]