parameters:
#    pronit_compras.example.class: Pronit\ComprasBundle\Example

services:
#    pronit_compras.example:
#        class: %pronit_compras.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
