parameters:
    pronit_compras_documentos_entradasmercancias.generador_items_finanzas.class: Pronit\ComprasBundle\Model\Documentos\EntradasMercancias\GeneradorItemsFinanzas
    pronit_compras_documentos_facturas.generador_items_finanzas.class: Pronit\ComprasBundle\Model\Documentos\Facturas\GeneradorItemsFinanzas
    
    pronit_compras_transaccion.entradamercancias.class: Pronit\ComprasBundle\Model\Transacciones\EntradasMercancias\TransaccionEntradaMercancias
    pronit_compras_transaccion.factura.class: Pronit\ComprasBundle\Model\Transacciones\Facturas\TransaccionFactura
    pronit_compras_transaccion.ordenpago.class: Pronit\ComprasBundle\Model\Transacciones\OrdenesPago\TransaccionOrdenPago
    
    pronit_compras_transformer.itemspagotransformer.class: Pronit\ComprasBundle\Form\DataTransformer\ItemsPagoTransformer

services:
    pronit_compras_documentos_entradasmercancias.generador_items_finanzas:
        class: %pronit_compras_documentos_entradasmercancias.generador_items_finanzas.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_customizing.operaciones_customizing_manager, @pronit_gestion_bienesyservicios_customizing_contabilidad.imputaciones_manager, @pronit_contabilidad_customizing.imputaciones_manager]        

    pronit_compras_documentos_facturas.generador_items_finanzas:
        class: %pronit_compras_documentos_facturas.generador_items_finanzas.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_customizing.operaciones_customizing_manager, @pronit_contabilidad_customizing.imputaciones_manager]        

    pronit_compras_transaccion.entradamercancias:
        class: %pronit_compras_transaccion.entradamercancias.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_compras_documentos_entradasmercancias.generador_items_finanzas, @pronit_contabilidad_customizing.generador_asientos_contables]

    pronit_compras_transaccion.factura:
        class: %pronit_compras_transaccion.factura.class%
        arguments: [@doctrine.orm.entity_manager, @pronit_compras_documentos_facturas.generador_items_finanzas, @pronit_contabilidad_customizing.generador_asientos_contables]        
        
    pronit_compras_transaccion.ordenpago:
        class: %pronit_compras_transaccion.ordenpago.class%
        arguments: [@doctrine.orm.entity_manager]
        
    pronit_compras_transformer.itemspagotransformer:
        class: %pronit_compras_transformer.itemspagotransformer.class%
        arguments: [@doctrine.orm.entity_manager]
        
