services:
    sonata.admin.sociedadco:
        class: Pronit\EstructuraEmpresaBundle\Admin\SociedadCOAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Estructura de empresa", label: "Sociedad CO" }
        arguments:
            - ~
            - Pronit\EstructuraEmpresaBundle\Entity\SociedadCO
            - ~
        calls:
            - [ setTranslationDomain, [PronitEstructuraEmpresaBundle]]   

    sonata.admin.sociedadgl:
        class: Pronit\EstructuraEmpresaBundle\Admin\SociedadGLAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Estructura de empresa", label: "Sociedad GL" }
        arguments:
            - ~
            - Pronit\EstructuraEmpresaBundle\Entity\SociedadGL
            - ~
        calls:
            - [ setTranslationDomain, [PronitEstructuraEmpresaBundle]]   
            
    sonata.admin.sociedadfi:
        class: Pronit\EstructuraEmpresaBundle\Admin\SociedadFIAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Estructura de empresa", label: "Sociedad FI" }
        arguments:
            - ~
            - Pronit\EstructuraEmpresaBundle\Entity\SociedadFI
            - ~
        calls:
            - [ setTranslationDomain, [PronitEstructuraEmpresaBundle]]   
            
    sonata.admin.varianteejerciciosociedad:
        class: Pronit\EstructuraEmpresaBundle\Admin\VarianteEjercicioSociedadAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Pronit\EstructuraEmpresaBundle\Entity\VarianteEjercicioSociedad
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]                                                