services:
    sonata.admin.tipodivisionadministrativa:
        class: Pronit\Geographic\CoreBundle\Admin\TipoDivisionAdministrativaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrizaci贸n General", label: "Tipo de Divisi贸n Administrativa" }
        arguments:
            - ~
            - Pronit\Geographic\CoreBundle\Entity\TipoDivisionAdministrativa
            - ~
        calls:
            - [ setTranslationDomain, [PronitGeographicCoreBundle]]
            
    sonata.admin.divisionadministrativa:
        class: Pronit\Geographic\CoreBundle\Admin\DivisionAdministrativaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrizaci贸n General", label: "Divisi贸n Administrativa" }
        arguments:
            - ~
            - Pronit\Geographic\CoreBundle\Entity\DivisionAdministrativa
            - ~
        calls:
            - [ setTranslationDomain, [PronitGeographicCoreBundle]]