
services:
    pronit_geographic.divisionadministrativa_metadatavalue_factory:
        class: Pronit\Geographic\CoreBundle\Model\MetadataValueProvider\Factory\DivisionAdministrativaMetadataValueFactory
        arguments: []

    pronit_geographic.divisionadministrativa_metadata_provider_factory:
        class: Bluegrass\Metadata\Bundle\MetadataBundle\Model\MetadataProvider\Factory\EntityTableMetadataProviderFactory
        arguments: [@doctrine.orm.entity_manager, '\Pronit\Geographic\CoreBundle\Entity\DivisionAdministrativa', @pronit_geographic.divisionadministrativa_metadatavalue_factory]
