services:
    sonata.admin.moneda:
        class: Pronit\ParametrizacionGeneralBundle\Admin\MonedaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Moneda" }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\Moneda
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]
            
#    sonata.admin.pais:
#        class: Pronit\ParametrizacionGeneralBundle\Admin\PaisAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Pais" }
#        arguments:
#            - ~
#            - Pronit\ParametrizacionGeneralBundle\Entity\Pais
#            - ~
#        calls:
#            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]            
            
    sonata.admin.varianteejercicio:
        class: Pronit\ParametrizacionGeneralBundle\Admin\VarianteEjercicioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Variante Ejercicio" }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\VarianteEjercicio
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]                        
            
    sonata.admin.periodovarianteejercicio:
        class: Pronit\ParametrizacionGeneralBundle\Admin\PeriodoVarianteEjercicioAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\PeriodoVarianteEjercicio
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]                                    
            
    sonata.admin.sistemamedicion:
        class: Pronit\ParametrizacionGeneralBundle\Admin\SistemaMedicionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Sistema de Medición" }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\SistemaMedicion
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]
            
    sonata.admin.escala:
        class: Pronit\ParametrizacionGeneralBundle\Admin\EscalaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\Escala
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]                                    

    sonata.admin.conversionsistemamedicion:
        class: Pronit\ParametrizacionGeneralBundle\Admin\ConversionSistemaMedicionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Conversión Sistema de Medición" }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\ConversionSistemaMedicion
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]
