services:
    sonata.admin.moneda:
        class: Pronit\ParametrizacionGeneralBundle\Admin\MonedaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Moneda" }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\Moneda
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]
            
    sonata.admin.pais:
        class: Pronit\ParametrizacionGeneralBundle\Admin\PaisAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parametrización General", label: "Pais" }
        arguments:
            - ~
            - Pronit\ParametrizacionGeneralBundle\Entity\Pais
            - ~
        calls:
            - [ setTranslationDomain, [PronitParametrizacionGeneralBundle]]            