parameters:
#    pronit_customizing.example.class: Pronit\CustomizingBundle\Example

services:
    pronit_customizing.operaciones_customizing_manager:
        class: Pronit\CustomizingBundle\Model\Operaciones\OperacionesCustomizingManager
        arguments: [ @doctrine.orm.entity_manager ]
