
services:
    pronit.controlling.aspectos.manager.imputa_objetoscosto:
        class: Pronit\CoreBundle\Model\Controlling\Aspectos\ImputaObjetoCostosManager
        arguments: [@doctrine.orm.entity_manager]        
        
    pronit.controlling.documentos.imputador_objetoscosto:
        class: Pronit\CoreBundle\Model\Controlling\Documentos\ImputadorObjetosCosto
        arguments: [@doctrine.orm.entity_manager, @pronit.controlling.repositories.gestionimputacion, @pronit.controlling.aspectos.manager.imputa_objetoscosto ]

    pronit.controlling.documentos.imputacionsecundaria.imputador_objetoscosto:
        class: Pronit\CoreBundle\Model\Controlling\Documentos\ImputacionSecundaria\ImputadorObjetosCosto
        arguments: [@doctrine.orm.entity_manager, @pronit.controlling.repositories.gestionimputacion, @pronit.controlling.aspectos.manager.imputa_objetoscosto ]
