services:
    pronit.core.personas.personafisica:
        class: Pronit\CoreBundle\Admin\Personas\PersonaFisicaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Persona Física" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\PersonaFisica
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]            
            
    pronit.core.personas.personajuridica:
        class: Pronit\CoreBundle\Admin\Personas\PersonaJuridicaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Persona Jurídica" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\PersonaJuridica
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                        
            
    pronit.core.personas.proveedor:
        class: Pronit\CoreBundle\Admin\Personas\ProveedorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Proveedor" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\Proveedor
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                                    
            
    sonata.core.contabilidad.movimientos:
        class: Pronit\CoreBundle\Admin\Contabilidad\Movimientos\MovimientoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad", label: "Libro diario" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Contabilidad\Movimientos\Movimiento
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]
            - [ setTemplate, [list, PronitCoreBundle:Movimientos:list.html.twig]]

    pronit.admin.core.impuestos.indicadorimpuestos:
        class: Pronit\CoreBundle\Admin\Impuestos\IndicadorImpuestosAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Finanzas", label: "Impuestos" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Impuestos\IndicadorImpuestos
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]            
            
            
    pronit.admin.core.impuestos.itemindicadorimpuestos:
        class: Pronit\CoreBundle\Admin\Impuestos\ItemIndicadorImpuestosAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Impuestos\ItemIndicadorImpuestos
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

    pronit.admin.core.operaciones.operacioncontable:
        class: Pronit\CoreBundle\Admin\Operaciones\OperacionContableAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Finanzas", label: "Operaciones contables" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Operaciones\OperacionContable
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                        
        