services:
    pronit.core.personas.personafisica:
        class: Pronit\CoreBundle\Admin\Personas\PersonaFisicaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Persona Física" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\PersonaFisica
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]            
            
    pronit.core.personas.personajuridica:
        class: Pronit\CoreBundle\Admin\Personas\PersonaJuridicaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Persona Jurídica" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\PersonaJuridica
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                        
            
    pronit.core.personas.proveedor:
        class: Pronit\CoreBundle\Admin\Personas\ProveedorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Proveedor" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\Proveedor
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                                    

    pronit.core.personas.deudor:
        class: Pronit\CoreBundle\Admin\Personas\DeudorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Terceros", label: "Deudor" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Personas\Deudor
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                                    

    pronit.core.customizing.deudores.deudorsociedadfi:
        class: Pronit\CoreBundle\Admin\Customizing\Deudores\DeudorSociedadFIAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Customizing Sociedad FI", label: "Gestión de Deudores" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Customizing\Deudores\DeudorSociedadFI
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                                    
            
    sonata.core.contabilidad.movimientos:
        class: Pronit\CoreBundle\Admin\Contabilidad\Movimientos\MovimientoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad", label: "Libro diario" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Contabilidad\Movimientos\Movimiento
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]
            - [ setTemplate, [list, PronitCoreBundle:Movimientos:list.html.twig]]

    pronit.admin.core.impuestos.indicadorimpuestos:
        class: Pronit\CoreBundle\Admin\Impuestos\IndicadorImpuestosAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Finanzas", label: "Impuestos" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Impuestos\IndicadorImpuestos
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]            
            
            
    pronit.admin.core.impuestos.itemindicadorimpuestos:
        class: Pronit\CoreBundle\Admin\Impuestos\ItemIndicadorImpuestosAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Impuestos\ItemIndicadorImpuestos
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

    pronit.admin.core.operaciones.operacioncontable:
        class: Pronit\CoreBundle\Admin\Operaciones\OperacionContableAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Finanzas", label: "Operaciones contables" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Operaciones\OperacionContable
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]                        

    pronit.admin.core.ventas.pedido:
        class: Pronit\CoreBundle\Admin\Documentos\Ventas\Pedidos\PedidoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Ventas", label: "Pedido de Venta" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Documentos\Ventas\Pedidos\Pedido
            - 'PronitCoreBundle:Documentos\Ventas\Pedidos\Pedido'
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

    pronit.admin.core.ventas.itempedido:
        class: Pronit\CoreBundle\Admin\Documentos\Ventas\Pedidos\ItemPedidoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Documentos\Ventas\Pedidos\ItemPedido
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

    pronit.admin.core.ventas.entradasmercancias:
        class: Pronit\CoreBundle\Admin\Documentos\Ventas\SalidasMercancias\SalidaMercanciasAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Ventas", label: "Salida de Mercancías" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Documentos\Ventas\SalidasMercancias\SalidaMercancias
            - 'PronitCoreBundle:Documentos\Ventas\SalidasMercancias\SalidaMercancias'
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]
            
    pronit.admin.core.ventas.itementradamercancias:
        class: Pronit\CoreBundle\Admin\Documentos\Ventas\SalidasMercancias\ItemSalidaMercanciasAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Documentos\Ventas\SalidasMercancias\ItemSalidaMercancias
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]
            
    pronit.admin.core.ventas.facturas.factura:
        class: Pronit\CoreBundle\Admin\Documentos\Ventas\Facturas\FacturaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Ventas", label: "Factura" }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Documentos\Ventas\Facturas\Factura
            - 'PronitCoreBundle:Documentos\Ventas\Facturas\Factura'
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]
            
    pronit.admin.core.ventas.facturas.itemfactura:
        class: Pronit\CoreBundle\Admin\Documentos\Ventas\Facturas\ItemFacturaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\Documentos\Ventas\Facturas\ItemFactura
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

    pronit.admin.core.bienesyservicios.presentaciones.presentacioncompra:
        class: Pronit\CoreBundle\Admin\BienesYServicios\Presentaciones\PresentacionCompraAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\BienesYServicios\Presentaciones\PresentacionCompra
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]
            
    pronit.admin.core.bienesyservicios.presentaciones.presentacionventa:
        class: Pronit\CoreBundle\Admin\BienesYServicios\Presentaciones\PresentacionVentaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\BienesYServicios\Presentaciones\PresentacionVenta
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

    pronit.admin.core.bienesyservicios.presentaciones.fraccionamiento:
        class: Pronit\CoreBundle\Admin\BienesYServicios\Presentaciones\FraccionamientoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: null }
        arguments:
            - ~
            - Pronit\CoreBundle\Entity\BienesYServicios\Presentaciones\Fraccionamiento
            - ~
        calls:
            - [ setTranslationDomain, [PronitCoreBundle]]

