parameters:
#    pronit_core.example.class: Pronit\CoreBundle\Example

services:
#    pronit_core.example:
#        class: %pronit_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
