parameters:
    pronit_contabilidad_customizing.imputaciones_manager.class: Pronit\CoreBundle\Model\Contabilidad\Customizing\ImputacionesCustomizingManager
    pronit_contabilidad_customizing.generador_asientos_contables.class: Pronit\CoreBundle\Model\Contabilidad\Movimientos\GeneradorAsientosContables
    pronit_core.numeracion_sociedadfi_manager.class: Pronit\CoreBundle\Model\Numeraciones\NumeracionSociedadFIManager
        
services:

    pronit_core.buscador_registro_condicion:
        class: Pronit\CoreBundle\Model\Automatizacion\Secuencias\BuscadorRegistroCondicion
        arguments: [@doctrine.orm.entity_manager, @bluegrass.metadata_provider_factory]
    
    pronit_core.registro_condicion_metadatavalue_factory:
        class: Pronit\CoreBundle\Model\Automatizacion\Secuencias\MetadataValueProvider\Factory\RegistroCondicionMetadataValueFactory
        arguments: []
    
    pronit_core.tablacondicion_metadata_provider_factory_locator:
        class: Pronit\CoreBundle\Model\Automatizacion\Secuencias\MetadataValue\Factory\Locator\TablaCondicionMetadataProviderFactoryLocator
        arguments: [@doctrine.orm.entity_manager, @pronit_core.registro_condicion_metadatavalue_factory]    
        
    pronit_core.numeracion_sociedadfi_manager:
        class: %pronit_core.numeracion_sociedadfi_manager.class%
        arguments: [@doctrine.orm.entity_manager]
        
    pronit_contabilidad_customizing.imputaciones_manager:
        class: %pronit_contabilidad_customizing.imputaciones_manager.class%
        arguments: [@doctrine.orm.entity_manager]

    pronit_contabilidad_customizing.generador_asientos_contables:
        class: %pronit_contabilidad_customizing.generador_asientos_contables.class%
        arguments: [@pronit_core.numeracion_sociedadfi_manager]
        
