services:
    sonata.admin.movimientos:
        class: Pronit\ContabilidadBundle\Admin\Movimientos\MovimientoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contabilidad", label: "Libro diario" }
        arguments:
            - ~
            - Pronit\ContabilidadBundle\Entity\Movimientos\Movimiento
            - ~
        calls:
            - [ setTranslationDomain, [PronitContabilidadBundle]]
            - [ setTemplate, [list, PronitContabilidadBundle:Movimientos:list.html.twig]]