parameters:
    pronit_contabilidad_customizing.imputaciones_manager.class: Pronit\ContabilidadBundle\Model\Customizing\ImputacionesCustomizingManager

services:
    pronit_contabilidad_customizing.imputaciones_manager:
        class: %pronit_contabilidad_customizing.imputaciones_manager.class%
        arguments: [@doctrine.orm.entity_manager]
