parameters:
#    pronit_contabilidad.example.class: Pronit\ContabilidadBundle\Example

services:
#    pronit_contabilidad.example:
#        class: %pronit_contabilidad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
